### PR TITLE
Add mongodb backend

### PR DESCRIPTION
**Pull request by ithinkihaveacat**

### CODE REVIEW

**Comment by vid** [comment]
Hi development team,

I'd really like to use a nodej caching proxy with hooks (for bayeux messages in my case), is this ready for use now or do you have a timeline?

thanks!

— users

**Comment by ithinkihaveacat** [comment]
@vid What sort of hooks do you want?  I've added a lot of hooks to this branch, because they're used internally.  The request listener itself will fire `newRequest` and `newResponse` events, and the cache and HTTP client backend will also fire similar events.

Note that you can't alter request or response bodies via the event listeners, only status codes and headers.  (The system is designed to transform headers, basically.)

**Comment by vid** [comment]
I'd have to install and work with it more to better understand. Does it work now? I notice you removed the startup examples so wasn't sure how to best get it going.

thanks!

**Comment by vid** [comment]
still hoping you might provide a simple "start it up" example, if it's currently functional (that's not clear).

in case you have a moment to help!, I've completely fallen for nodejs and am taking a deep dive (sometimes feeling like I'm drowning, hah hah). the project I'm working on is a research project where we identify entities from websites. I want to use a caching proxy to avoid abusing the websites, and to inject some js instrumentation into the pages.

**Comment by ithinkihaveacat** [comment]
@vid I've added an example back in now, but please note that this code is all pretty rough!  What were you wanting to do?  If you can let me know what you're wanting to do in some detail I can give you some idea how to achieve it, or indeed let you know if fishback is suitable!

**Comment by vid** [comment]
thanks for asking! what we're doing is working with content specific web sites, such as health and science. we're using a backend text mining tool, and would like to find a way to interactively annotate pages, and update what's to be annotated. We messed around with userscripts for a while, but they have a number of drawbacks. I think a proxy approach will be better. I specifically want a caching server, in order to avoid abusing web sites, but also so updated content can be stored and I can index the content. But I need to inject some javascript instrumentation to served pages. I also want to be able to intercept calls, and add client-server interaction. I would also like to support https.

I've managed to get everything but caching and https working based on https://github.com/ayurmedia/proxy. thanks @ayurmedia! Working around issues related to gzipped pages was interesting, and it still has some glitches with some sites. It uses bayeux pubsub. I can upload that if interested. But I'd rather not reinvent the caching wheel. However I'm not sure if you're interested in rewriting content, and how https fits in.

**Pull request merged**
